version: '3.8'
services:

  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      env_file: .env
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mongo:latest
    volumes:
      - db-store:/data/db  
  nginx:
    restart: always
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - app
  test:
    build: .
    command: npm test

volumes:
  db-store:

